<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add';

$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuarios', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo "<br>";
echo $this->formRow($form->get('nombre'));
echo "<br>";
echo $this->formRow($form->get('puesto'));
echo "<br>";
echo $this->formRow($form->get('area'));
echo "<br>";

echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  ";

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();