
<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>You want to delete the record ?
	<br>
	<br>
    Usuario:  '<?php echo $this->escapeHtml($usuarios->nombre); ?>' 
    <br>
    <br>
    Puesto:   '<?php echo $this->escapeHtml($usuarios->puesto); ?>'
    <br>
    <br>
     Area:   '<?php echo $this->escapeHtml($usuarios->area); ?>'
    <br>
    <br>
</p>
<?php

$url = $this->url('usuarios', array(

    'action' => 'delete',

    'id' => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $usuarios->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>