<?php

$title = 'Edit';

$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br>
<br>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuarios',
												    array(
												        'action' => 'edit',
												        'id' => $this->id,
												    )
												));
$form->prepare();
echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
echo "<br><br>";
echo $this->formRow($form->get('nombre'));
echo "<br><br>";
echo $this->formRow($form->get('puesto'));
echo "<br><br>";
echo $this->formRow($form->get('area'));
echo "<br><br>";


echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();